"""Botoraptor SDK compatibility wrapper over the legacy chatlayer_sdk package."""

from chatlayer_sdk import (
    Attachment,
    AttachmentType,
    Botoraptor,
    BotoraptorAPIError,
    BotoraptorConfig,
    BotoraptorError,
    ChatLayer,
    ChatLayerAPIError,
    ChatLayerConfig,
    ChatLayerError,
    FileUploadByUrlOptions,
    FileUploadOptions,
    GetMessagesParams,
    GetRoomsParams,
    ListenerType,
    Message,
    MessageType,
    RoomInfo,
    RoomsResponse,
    ServerResponse,
    User,
)

__version__ = "1.4.0"
__all__ = [
    "Attachment",
    "AttachmentType",
    "Botoraptor",
    "BotoraptorAPIError",
    "BotoraptorConfig",
    "BotoraptorError",
    "ChatLayer",
    "ChatLayerAPIError",
    "ChatLayerConfig",
    "ChatLayerError",
    "FileUploadByUrlOptions",
    "FileUploadOptions",
    "GetMessagesParams",
    "GetRoomsParams",
    "ListenerType",
    "Message",
    "MessageType",
    "RoomInfo",
    "RoomsResponse",
    "ServerResponse",
    "User",
]
